# For max. versions see https://go2docs.graylog.org/current/downloading_and_installing_graylog/red_hat_installation_os.htm

services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: "mongo:8"  
    #restart: "on-failure"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - graylog
    volumes:
      - "mongodb_data:/data/db"
      - "mongodb_config:/data/configdb"  
  
  opensearch:
    image: opensearchproject/opensearch:2.15.0
    container_name: opensearch
    hostname: opensearch
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
      # Can generate a password for `OPENSEARCH_INITIAL_ADMIN_PASSWORD` using a linux device via:
      # tr -dc A-Z-a-z-0-9_@#%^-_=+ < /dev/urandom  | head -c${1:-32}
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD="@admin@1234567890@ABC"
      - TZ=Asia/Shanghai
    ports:
      - "9200:9200"
    networks:
      - graylog  
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536

  # Graylog: https://hub.docker.com/r/graylog/graylog-enterprise
  graylog:
    hostname: "server"
    build: 
      context: .
      dockerfile: ./Graylog-Custom.Dockerfile
    depends_on:
      mongodb:
        condition: "service_started"
      opensearch:
        condition: "service_started"
    entrypoint: "/usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/data/node-id"
      #Login @ http://127.0.0.1:9000 with user=admin and password=<GRAYLOG_PASSWORD_SECRET>
      GRAYLOG_PASSWORD_SECRET: "admin1234567890ABC"
      GRAYLOG_ROOT_PASSWORD_SHA2: "FFC7D1D049BA9273DF5D69114E5AD1AD291D93F99E5465992AD7AD3E50AA4263"
      GRAYLOG_REPORT_DISABLE_SANDBOX: true
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_ELASTICSEARCH_HOSTS: http://opensearch:9200
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
      TZ: Asia/Shanghai
    ports:
    - "5044:5044/tcp"   # Beats
    - "5140:5140/udp"   # Syslog
    - "5140:5140/tcp"   # Syslog
    - "5555:5555/tcp"   # RAW TCP
    - "5555:5555/udp"   # RAW UDP
    - "9000:9000/tcp"   # Server API
    - "12201:12201/tcp" # GELF TCP
    - "12201:12201/udp" # GELF UDP
    #- "10000:10000/tcp" # Custom TCP port
    #- "10000:10000/udp" # Custom UDP port
    - "13301:13301/tcp" # Forwarder data
    - "13302:13302/tcp" # Forwarder config
    networks:
      - graylog
    volumes:
      - "graylog_data:/usr/share/graylog/data/data"
    restart: "on-failure"

networks:
  graylog:
    driver: "bridge"

volumes:
  mongodb_data:
  mongodb_config:
  graylog-datanode:
  graylog_data:
  opensearch_data:
